---
- name: Check if timedatectl is present
  stat:
    path: /usr/bin/timedatectl
  register: stat_res
  tags: tomcat_conf

- name: Determine system timezone
  shell: |
    set -o pipefail
    timedatectl status |grep 'Time zone' |cut -d ':' -f 2 |cut -d '(' -f 1 |sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e 's/_/ /g'
  register: res
  changed_when: False
  check_mode: no
  tags: tomcat_conf

- name: Set current_timezone
  set_fact: current_timezone={{ res.stdout }}
  tags: tomcat_conf

- name: Validate current_timezone
  fail:
    msg: Unable to detect timezone. You must specify the current_timezone var
  when: current_timezone is not defined
  tags: tomcat_conf

- debug:
    msg: "Timezone detected: {{ current_timezone }} - This can be overidden with the current_timezone variable"
  tags: tomcat_conf
