---
- name: Set basename for self-signed cert
  set_fact:
    tomcat_ssl_cert_basename: "{{ ansible_fqdn }}-self-signed"
  tags: tomcat_conf

- name: Set facts for self-signed cert
  set_fact:
    tomcat_ssl_enabled: yes
    tomcat_ssl_cert_attrs:
      certificateKeyFile: "{{ tomcat_root }}/conf/{{ tomcat_ssl_cert_basename }}-key.pem"
      certificateFile: "{{ tomcat_root }}/conf/{{ tomcat_ssl_cert_basename }}-cert.pem"
  tags: tomcat_conf

- name: Generate an OpenSSL private key
  openssl_privatekey:
    path: "{{ tomcat_root }}/conf/{{ tomcat_ssl_cert_basename }}-key.pem"
    owner: "{{ tomcat_ssl_private_key_owner }}"
    group: "{{ tomcat_group }}"
    mode: "0640"
  tags: tomcat_conf

#
# This does not work on RHEL 7 because of:
#   https://github.com/ansible/ansible/issues/34054
#
# Should be resolved by:
#   https://github.com/ansible/ansible/issues/34054
#
# TODO: This issue was resolved in 2019, may want to switch back to this approach.
#
# - name: Generate an OpenSSL CSR
#   openssl_csr:
#     path: "{{ tomcat_root }}/conf/{{ tomcat_ssl_cert_basename }}.csr"
#     privatekey_path: "{{ tomcat_root }}/conf/{{ tomcat_ssl_cert_basename }}-key.pem"
#     common_name: "{{ ansible_hostname }}"
#
# - name: Generate a {{ tomcat_ssl_cert_basename }} OpenSSL certificate
#   openssl_certificate:
#     path: "{{ tomcat_root }}/conf/{{ tomcat_ssl_cert_basename }}-cert.pem"
#     privatekey_path: "{{ tomcat_root }}/conf/{{ tomcat_ssl_cert_basename }}-key.pem"
#     csr_path: "{{ tomcat_root }}/conf/{{ tomcat_ssl_cert_basename }}.csr"
#     provider: selfsigned
#     owner: "{{ tomcat_ssl_private_key_owner }}"
#     group: "{{ tomcat_group }}"
#     mode: "0644"

#
# Workaround:
#
- name: Generate an OpenSSL CSR configuration
  template:
    src: csr_conf.j2
    dest: "{{ tomcat_root }}/conf/{{ tomcat_ssl_cert_basename }}.cnf"
  tags: tomcat_conf

- name: Generate a CSR
  command: "openssl req -key {{ tomcat_root }}/conf/{{ tomcat_ssl_cert_basename }}-key.pem -new -out {{ tomcat_root }}/conf/{{ tomcat_ssl_cert_basename }}.csr -config {{ tomcat_root }}/conf/{{ tomcat_ssl_cert_basename }}.cnf"
  args:
    creates: "{{ tomcat_root }}/conf/{{ tomcat_ssl_cert_basename }}.csr"
  tags: tomcat_conf

- name: Generate a {{ tomcat_ssl_cert_basename }} certificate
  command: "openssl x509 -signkey {{ tomcat_root }}/conf/{{ tomcat_ssl_cert_basename }}-key.pem -in {{ tomcat_root }}/conf/{{ tomcat_ssl_cert_basename }}.csr -req -days 9999 -out {{ tomcat_root }}/conf/{{ tomcat_ssl_cert_basename }}-cert.pem"
  args:
    creates: "{{ tomcat_root }}/conf/{{ tomcat_ssl_cert_basename }}-cert.pem"
  tags: tomcat_conf
