---
# TODO: Make a single backup instead of using per-task backups

# server.xml often has passwords in it, so limit access
- name: Set server.xml file permissions
  file:
    path: "{{ tomcat_server_xml_path }}"
    owner: "{{ tomcat_user }}"
    mode: "0600"
  tags: tomcat_conf

- name: Set shutdown port
  xml:
    path: "{{ tomcat_server_xml_path }}"
    xpath: /Server
    attribute: port
    value: "{{ tomcat_shutdown_port|string }}"
    pretty_print: yes
    backup: yes
  tags: tomcat_conf

- name: Set HTTP port
  xml:
    path: "{{ tomcat_server_xml_path }}"
    xpath: /Server/Service/Connector[starts-with(@protocol,'HTTP/')]
    attribute: port
    value: "{{ tomcat_http_port|string }}"
    pretty_print: yes
    backup: yes
  tags: tomcat_conf

- name: Enable x-forwarded headers
  xml:
    path: "{{ tomcat_server_xml_path }}"
    xpath: /Server/Service/Engine/Host/Valve[@className="org.apache.catalina.valves.RemoteIpValve"]
    attribute: protocolHeader
    value: X-Forwarded-Proto
    pretty_print: yes
    backup: yes
  when: tomcat_x_forwarded_enable
  tags: tomcat_conf

# TODO: If the AJP connector has previously been deleted, then this will not work.
- name: Set AJP port
  xml:
    path: "{{ tomcat_server_xml_path }}"
    xpath: /Server/Service/Connector[starts-with(@protocol,'AJP/')]
    attribute: port
    value: "{{ tomcat_ajp_port|string }}"
    pretty_print: yes
    backup: yes
  when: tomcat_ajp_enabled
  tags: tomcat_conf

- name: Disable AJP
  xml:
    path: "{{ tomcat_server_xml_path }}"
    xpath: /Server/Service/Connector[starts-with(@protocol,'AJP/')]
    state: absent
    pretty_print: yes
    backup: yes
  when: not tomcat_ajp_enabled
  tags: tomcat_conf

- name: Add Tomcat resources
  tomcat_resource:
    catalina_home: "{{ tomcat_root }}"
    name: "{{ item.name }}"
    attrs: "{{ item.attrs }}"
  with_items: "{{ tomcat_resources }}"
  no_log: tomcat_censor_ansible_output
  tags: tomcat_conf

- name: Remove SSL connector
  xml:
    path: "{{ tomcat_server_xml_path }}"
    pretty_print: yes
    backup: yes
    xpath: /Server/Service/Connector[@SSLEnabled="true"]
    state: absent
  when: not tomcat_ssl_enabled
  tags: tomcat_conf

- name: Set SSL connector parameters
  xml:
    path: "{{ tomcat_server_xml_path }}"
    pretty_print: yes
    backup: yes
    xpath: /Server/Service/Connector[@SSLEnabled="true"]
    attribute: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    port: "{{ tomcat_https_port }}"
    protocol: "{{ tomcat_ssl_protocol }}"
    maxThreads: "{{ tomcat_ssl_max_threads }}"
  when: tomcat_ssl_enabled
  tags: tomcat_conf

- name: Set certificate configuration configuration
  xml:
    path: "{{ tomcat_server_xml_path }}"
    pretty_print: yes
    backup: yes
    xpath: /Server/Service/Connector/SSLHostConfig/Certificate
    attribute: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ tomcat_ssl_cert_attrs }}"
  when: tomcat_ssl_enabled
  tags: tomcat_conf
