---
# TODO: Make a single backup instead of using per-task backups

- name: Set shutdown port
  xml:
    path: "{{ tomcat_server_xml_path }}"
    xpath: /Server
    attribute: port
    value: "{{ tomcat_shutdown_port|string }}"
    pretty_print: yes
    backup: yes

- name: Set HTTP port
  xml:
    path: "{{ tomcat_server_xml_path }}"
    xpath: /Server/Service/Connector[starts-with(@protocol,'HTTP/')]
    attribute: port
    value: "{{ tomcat_http_port|string }}"
    pretty_print: yes
    backup: yes

- name: Set AJP port
  xml:
    path: "{{ tomcat_server_xml_path }}"
    xpath: /Server/Service/Connector[starts-with(@protocol,'AJP/')]
    attribute: port
    value: "{{ tomcat_ajp_port|string }}"
    pretty_print: yes
    backup: yes

- name: Add Tomcat resources
  tomcat_resource:
    catalina_home: "{{ tomcat_root }}"
    name: "{{ item.name }}"
    attrs: "{{ item.attrs }}"
  with_items: "{{ tomcat_resources }}"

- name: Remove SSL connector
  xml:
    path: "{{ tomcat_server_xml_path }}"
    pretty_print: yes
    backup: yes
    xpath: /Server/Service/Connector[@SSLEnabled="true"]
    state: absent
  when: not tomcat_ssl_enabled

- name: Set SSL connector parameters
  xml:
    path: "{{ tomcat_server_xml_path }}"
    pretty_print: yes
    backup: yes
    xpath: /Server/Service/Connector[@SSLEnabled="true"]
    attribute: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    port: "{{ tomcat_https_port }}"
    protocol: "{{ tomcat_ssl_protocol }}"
    maxThreads: "{{ tomcat_ssl_max_threads }}"
  when: tomcat_ssl_enabled

- name: Set certificate configuration configuration
  xml:
    path: "{{ tomcat_server_xml_path }}"
    pretty_print: yes
    backup: yes
    xpath: /Server/Service/Connector/SSLHostConfig/Certificate
    attribute: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ tomcat_ssl_cert_attrs }}"
  when: tomcat_ssl_enabled
