---
- name: Download Tomcat
  get_url:
    url: "{{ tomcat_zip_url }}"
    dest: "{{ stage_dir }}/{{ tomcat_inst_name }}.zip"
    checksum: "{{ tomcat_zip_hash }}"

# The root of the Tomcat zip is a directory. This directory might not be
# what we want to name the Tomcat root. To accomodate this we first unarchive
# to a temporary directory in the staging area. We then move the directory
# the zip created to it's destination and possibly rename it.
#
# TODO: We might also want to introduce a variable allowing user control of
#       where the temp files are expanded.
- name: Create temporary staging area
  tempfile:
    state: directory
  register: tempdir

- name: Unzip Tomcat
  unarchive:
    src: "{{ stage_dir }}/{{ tomcat_inst_name }}.zip"
    dest: "{{ tempdir.path }}"
    copy: no

- name: Deploy Tomcat
  command: mv "{{ tempdir.path }}/{{ tomcat_zip_root_dir }}" "{{ tomcat_root }}"
  when: true # This whole file only gets executed when there's something to do.
             # We use the when:true to satisfy the linting tool.

- name: Remove temporary directory
  file:
    path: "{{ tempdir.path }}"
    state: absent

- name: Remove Tomcat-delivered webapps
  file:
    path: "{{ tomcat_root  }}/webapps/{{ item }}"
    state: absent
  with_items: "{{ tomcat_delivered_apps }}"
  when: tomcat_remove_delivered_apps
