---

- name: Converge
  hosts: all
  gather_facts: false

  vars:
    current_timezone: UTC
    stage_dir: /tmp
    tomcat_java_home: /etc/alternatives/java_sdk

    tomcat_version: 8.5.99
    tomcat_manage_webapps: yes
    tomcat_migrate_to_managed_webapps: yes

  roles:
    - tomcat
